from abc import ABC, abstractmethod

class NetworkMode(ABC):
    @abstractmethod
    def start_arp(self):...
    @abstractmethod
    def stop_arp(self):...

class HardwareNetworkMode(NetworkMode):
    def __init__(self):
        self.buffer = ...
        self.queue = ...

    def start(self):...
    def stop(self):...